stages:
- test
- deploy

unit-tests:
  stage: test
  image: python:3.9
  script:
    - python3 -m pip install -r tools/calver/requirements.txt
    - python3 -m pytest tools/calver/

tagging:
  stage: deploy
  image: docker:latest
  timeout: 3 hours
  services:
    - docker:dind
  before_script:
    - apk update && apk add git python3 py-pip
    - git remote remove origin
    - git config --global user.name "Git versioning"
    - git config --global user.email ""
    - git remote add origin https://CI_BOT:$CI_KEY@git.rz.tu-bs.de/akustik/software-versioning-example
    - git status
  script:
    - python3 -m pip install -r tools/calver/requirements.txt
    - python3 tools/calver/cCalVer.py $CI_COMMIT_BRANCH
    - cat version.txt
    - source version.txt
    - echo $SOFTWARE_CALVER
    - git tag -a $SOFTWARE_CALVER -m "Release version $SOFTWARE_CALVER"
    - git push origin $SOFTWARE_CALVER
  artifacts:
    paths:
      - version.txt
  rules:
    - if: $CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH
      when: never
    - if: $CI_COMMIT_TAG
      when: never
    - when: always