stages:
- test
- release

unit-tests:
  stage: test
  image: python:3.9
  script:
    - python3 -m pip install -r tools/calver/requirements.txt
    - python3 -m pytest tools/calver/

version:
  stage: release
  image: docker:latest
  timeout: 3 hours
  services:
    - docker:dind
  script:
    - apk update && apk add git python3 py-pip
    - python3 -m pip install -r tools/calver/requirements.txt
    - python3 tools/calver/cCalVer.py
    - cat version.txt
    - ls
    - git status
    - source version.txt
    - echo $SOFTWARE_CALVER
