name: CI/CD

on:
  push:
    branches:
      - '*'

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install all dependencies
      run: python -m pip install -r tools/calver/requirements.txt

    - name: Run unit tests
      run: python -m pytest tools/calver/
