name: CI/CD

on:
  push:
    branches:
      - '*'

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install all dependencies
      run: python -m pip install -r tools/calver/requirements.txt

    - name: Run unit tests
      run: python -m pytest tools/calver/

  tagging:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git python3 python3-pip
          
      - name: Configure Git
        run: |
          git remote remove origin
          git config --global user.name "Git versioning"
          git config --global user.email ""
          git remote add origin https://CI_BOT:$CI_KEY@github.com/hksreekumar/CalVer
          git status
          python3 -m pip install -r tools/calver/requirements.txt
          python3 tools/calver/cCalVer.py master
          cat version.txt
          source version.txt
          echo $SOFTWARE_CALVER
          git tag -a $SOFTWARE_CALVER -m "Release version $SOFTWARE_CALVER"
          git push origin $SOFTWARE_CALVER

      - name: Upload Version File
        uses: actions/upload-artifact@v2
        with:
          name: version-artifact
          path: version.txt

    if: |
      github.ref != 'refs/heads/main' && !startsWith(github.ref, 'refs/tags/')
